# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godirgen < Formula
  desc ""
  homepage "https://github.com/rexsimiloluwah/godirgen"
  version "0.1.3"

  on_macos do
    url "https://github.com/rexsimiloluwah/godirgen/releases/download/v0.1.3/godirgen_0.1.3_darwin_all.tar.gz"
    sha256 "b3d89e2f61f1cbd80d338f725b3874f4c9d900262bcd915f53b79bf10b57c183"

    def install
      bin.install "godirgen"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rexsimiloluwah/godirgen/releases/download/v0.1.3/godirgen_0.1.3_linux_amd64.tar.gz"
      sha256 "5bdd86d477a14427ce2806e55d9271ea999289553eff7fe5a48d73e09f379f97"

      def install
        bin.install "godirgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexsimiloluwah/godirgen/releases/download/v0.1.3/godirgen_0.1.3_linux_arm64.tar.gz"
      sha256 "b57647fbbbbbc80a7b8f948d8d8354827ea23a6fd03df51343cc50de6d9b1811"

      def install
        bin.install "godirgen"
      end
    end
  end
end
