# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godirtreegen < Formula
  desc ""
  homepage "https://github.com/rexsimiloluwah/godirtreegen"
  version "0.1.6"

  on_macos do
    url "https://github.com/rexsimiloluwah/godirtreegen/releases/download/v0.1.6/godirtreegen_0.1.6_darwin_all.tar.gz"
    sha256 "60c43f5a073b57c6caac5159a94cbb1b2e23e5abceb5dd0264a5b34156e0e954"

    def install
      bin.install "godirtreegen"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rexsimiloluwah/godirtreegen/releases/download/v0.1.6/godirtreegen_0.1.6_linux_amd64.tar.gz"
      sha256 "93930608d7dc3b6bde01f9fd7954c6387e1fcf9139ecf336cc19be49f7b2626a"

      def install
        bin.install "godirtreegen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexsimiloluwah/godirtreegen/releases/download/v0.1.6/godirtreegen_0.1.6_linux_arm64.tar.gz"
      sha256 "26c29d266dd723062f3322d882e9a708b65cc9115560adb60a8412d0b4ffeac8"

      def install
        bin.install "godirtreegen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rexsimiloluwah/godirtreegen/releases/download/v0.1.6/godirtreegen_0.1.6_linux_armv6.tar.gz"
      sha256 "11c91d1454163f42093ade6d4c6b52791012198727cba4855afc7785a50ee93a"

      def install
        bin.install "godirtreegen"
      end
    end
  end
end
