# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godirgen < Formula
  desc ""
  homepage "https://github.com/rexsimiloluwah/godirgen"
  version "0.1.2"

  on_macos do
    url "https://github.com/rexsimiloluwah/godirgen/releases/download/v0.1.2/godirgen_0.1.2_darwin_all.tar.gz"
    sha256 "09a45d7bf9eaf0a979f4d83980984e5929a50c499cc22116a7bcf1a327ceb68c"

    def install
      bin.install "godirgen"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rexsimiloluwah/godirgen/releases/download/v0.1.2/godirgen_0.1.2_linux_amd64.tar.gz"
      sha256 "783f76da4e121984e7563a4c916cd2bc2651dd238fefe99f60c1bac88be99f37"

      def install
        bin.install "godirgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexsimiloluwah/godirgen/releases/download/v0.1.2/godirgen_0.1.2_linux_arm64.tar.gz"
      sha256 "66ecae0999dd57eff17eda4a69b5d88120de9f9a443ea7c3187125460b14a46d"

      def install
        bin.install "godirgen"
      end
    end
  end
end
